hash-format = "sha256"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"

[[files]]
file = "config/yosbr/config/bigpony.json"

[[files]]
file = "config/yosbr/config/modmenu.json"

[[files]]
file = "mods/ad-astra.pw.toml"
metafile = true

[[files]]
file = "mods/adorn.pw.toml"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
metafile = true

[[files]]
file = "mods/better-archeology.pw.toml"
metafile = true

[[files]]
file = "mods/big-pony.pw.toml"
metafile = true

[[files]]
file = "mods/blockus.pw.toml"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/clear-void.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
metafile = true

[[files]]
file = "mods/create-air-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
metafile = true

[[files]]
file = "mods/create-diesel-generators-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-enchantment-industry-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-fabric-sodium-fix.pw.toml"
metafile = true

[[files]]
file = "mods/create-garnished.pw.toml"
metafile = true

[[files]]
file = "mods/create-goggles.pw.toml"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
metafile = true

[[files]]
file = "mods/create-ore-excavation.pw.toml"
metafile = true

[[files]]
file = "mods/create-power-loader-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/create-structures.pw.toml"
metafile = true

[[files]]
file = "mods/create-track-map.pw.toml"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
metafile = true

[[files]]
file = "mods/dimensionaldoors.pw.toml"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
metafile = true

[[files]]
file = "mods/effective.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi-ores.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/emiffect.pw.toml"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
metafile = true

[[files]]
file = "mods/endrem.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/extended-cogwheels.pw.toml"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/hd-skins.pw.toml"
metafile = true

[[files]]
file = "mods/htm.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-holidays.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-paintings.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
metafile = true

[[files]]
file = "mods/megane.pw.toml"
metafile = true

[[files]]
file = "mods/memory-usage-screen.pw.toml"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
metafile = true

[[files]]
file = "mods/mine-little-pony.pw.toml"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
metafile = true

[[files]]
file = "mods/opac-fabric-create-support.pw.toml"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/pick-your-poison.pw.toml"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
metafile = true

[[files]]
file = "mods/rechiseled-create.pw.toml"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/reinforced-barrels.pw.toml"
metafile = true

[[files]]
file = "mods/reinforced-chests.pw.toml"
metafile = true

[[files]]
file = "mods/reinforced-shulker-boxes.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/satin-api.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/the-lost-castle.pw.toml"
metafile = true

[[files]]
file = "mods/thin-air.pw.toml"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
metafile = true

[[files]]
file = "mods/timeoutout.pw.toml"
metafile = true

[[files]]
file = "mods/toms-peripherals.pw.toml"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/unicopia.pw.toml"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-menu-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true
