name = "SkyCraft1"
author = "Fauli1221"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0-beta.8"

[options]
acceptable-game-versions = ["1.20"]
no-internal-hashes = true
